In [1]:
import pandas as pd
import requests

In [2]:
API_TOKEN = "tqz8BHX2O0tyVADTRuvyBaGmLVrZkwcwrhfbRjR9T5ZAQWXovTUeBytl4onZ"
params = {"api_token": API_TOKEN, "include": "timeline"}

In [3]:
data = requests.get("https://api.sportmonks.com/v3/football/fixtures/19146817", params=params).json()["data"]
match = pd.json_normalize(data)

In [4]:
timeline = pd.json_normalize(match.timeline[0])
len(timeline)

17

In [5]:
timeline.head(5)

,id,fixture_id,period_id,participant_id,type_id,section,player_id,related_player_id,player_name,related_player_name,...,info,addition,minute,extra_minute,injured,on_bench,coach_id,sub_type_id,detailed_period_id,sort_order
0,148273597,19146817,5800865,246,126,timeline,None,None,None,None,...,None,3rd Corner,37,NaN,None,False,None,None,None,3
1,148273435,19146817,5800865,246,126,timeline,None,None,None,None,...,None,1st Corner,6,NaN,None,False,None,None,None,1
2,148273535,19146817,5800865,246,126,timeline,None,None,None,None,...,None,2nd Corner,24,NaN,None,False,None,None,None,2
3,148273629,19146817,5800865,273,126,timeline,None,None,None,None,...,None,6th Corner,38,NaN,None,False,None,None,None,6
4,148273735,19146817,5800865,273,126,timeline,None,None,None,None,...,None,8th Corner,45,NaN,None,False,None,None,None,8